num1=int(input("Enter the integer:"))
num2=int(input("enter the integer:"))
print("bitwise & operator:",num1&num2)
print("---------")
print("bitwise | operator:",num1|num2)
print("---------")
print("bitwise ^ operator:",num1^num2)
print("---------")
print("bitwise ~ operator:",~num1)
print("----------")
print("bitwise left shift operator:",num1<<num2)
print("-----------")
print("bitwise right shift operator:",num1>>num2)