prgm_lng=['python','java','c','c++','SQL','PHP']
print(prgm_lng)
print(type(prgm_lng))
print("----------------------------------------")
print("Accessing the list elements using positive indexing")
print(prgm_lng[0])
print(prgm_lng[1])
print(prgm_lng[2])
print(prgm_lng[3])
print(prgm_lng[4])
print(prgm_lng[5])
print("------------------------------------------")
print("Accessing list elements with negative indexing")
print(prgm_lng[-6])
print(prgm_lng[-5])
print(prgm_lng[-4])
print(prgm_lng[-3])
print(prgm_lng[-2])
print(prgm_lng[-1])