n1=int(input("enter the 1st integer:"))
n2=int(input("Enter the 2nd integer:"))
print("Before swapping:")
print("num1=",n1)
print("num2=",n2)
print("After swapping:")
print("num1=",n2)
print("num2=",n1)
#without variable
print("------Without varible------")
print("Before swapping:")
print("num1=",n1)
print("num2=",n2)
n1,n2=n2,n1
print("After swapping:")
print("num1=",n1)
print("num2=",n2)